# Generated by Django 3.2.6 on 2021-09-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('meta_title', models.CharField(max_length=120, null=True, unique=True, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(max_length=250, null=True, unique=True, verbose_name='Мета описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/image/', verbose_name='Изображение')),
                ('alt_img', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt')),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(max_length=255, null=True, verbose_name='Краткое описание')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'posts',
                'ordering': ['title'],
            },
        ),
    ]
